/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Model.NguoiChoi;
import Model.TranDau;
import Service.ClientProcess;

/**
 *
 * @author HP
 */
public class GDChonHoacTaoPhongFrame extends javax.swing.JFrame {

    /**
     * Creates new form GDChonHoacTaoPhongFrame
     */
    NguoiChoi nguoiChoi;
    ClientProcess clientProcess;
    public GDChonHoacTaoPhongFrame(ClientProcess clientProcess,NguoiChoi nguoiChoi) {
        initComponents();
        this.clientProcess = clientProcess;
        this.nguoiChoi = nguoiChoi;
        
        btnTaoPhong.addActionListener((e) -> {
            TranDau tranDau = new TranDau();
            String code = txtCode.getText();
            tranDau.setCode(code);
            TranDau tranDauFromServer = this.clientProcess.taoTranDau(tranDau,nguoiChoi.getId());
            if(tranDauFromServer != null){
                GDDanhCo gdDanhCo = new GDDanhCo(nguoiChoi,clientProcess);
                this.dispose();
            }
        });
        
        btnVaoPhong.addActionListener((e)->{
            TranDau tranDau = new TranDau();
            String code = txtCode.getText();
            tranDau.setCode(code);
            TranDau tranDauFromServer = this.clientProcess.vaoTranDau(tranDau, nguoiChoi.getId());
            if(tranDauFromServer != null){
                GDDanhCo gdDanhCo = new GDDanhCo(nguoiChoi,clientProcess);
                this.dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        txtCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVaoPhong = new javax.swing.JButton();
        btnTaoPhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        btnVaoPhong.setText("Vào Phòng");

        btnTaoPhong.setText("Tạo Phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVaoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnVaoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTaoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoPhong;
    private javax.swing.JButton btnVaoPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
